### ISSUE TITLE
新增了账号绑定deviceID

### ISSUE THREAD

**Issue by s78910** [ALNthy/asyncYibanAutoSgin#1]
大佬您好，受益于您的项目，已经连续自动签到很久了，解放了双手。 但是最近我们学校，开始绑定设备了。每个帐号绑定一个deviceID，这个东西在 def submit那里添加一条session.get("[https://xsgl.jlau.edu.cn/nonlogin/yiban/authQYY.htm?deviceId\u003d********************（这一段**就是设备ID](https://xsgl.jlau.edu.cn/nonlogin/yiban/authQYY.htm?deviceId%5Cu003d********************%EF%BC%88%E8%BF%99%E4%B8%80%E6%AE%B5**%E5%B0%B1%E6%98%AF%E8%AE%BE%E5%A4%87ID) 一共64个字符） 。 想要认证成功就必须添加这段，然后这个deviceID必须ROOT才能抓包抓出来，有什么办法可以跳过 或者有什么方法在root设备上登录其他帐号查出来帐号所属的deviceID吗 ？

**Comment by ALNthy** [comment]
每个学校的校本化认证都不太一样，本项目的接口大都是从 https://c.uyiban.com/#/ 所抓取的
如果你有兴趣可以通过pc端开发者工具修改user-agent成Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)  Mobile/15E148 yiban_iOS/5.0 来访问该网址，进行校本化认证并抓包。或许能找到解决方法
